/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as FeaturesRouteRouteImport } from './routes/_features/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as FeaturesIndexRouteImport } from './routes/_features/index'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as FeaturesTrainingsIndexRouteImport } from './routes/_features/trainings/index'
import { Route as FeaturesTimesheetIndexRouteImport } from './routes/_features/timesheet/index'
import { Route as FeaturesResearchIndexRouteImport } from './routes/_features/research/index'
import { Route as FeaturesProjectsIndexRouteImport } from './routes/_features/projects/index'
import { Route as FeaturesManageAccountsIndexRouteImport } from './routes/_features/manage-accounts/index'
import { Route as FeaturesGameIndexRouteImport } from './routes/_features/game/index'
import { Route as FeaturesEngagementsIndexRouteImport } from './routes/_features/engagements/index'
import { Route as FeaturesDirectoryIndexRouteImport } from './routes/_features/directory/index'
import { Route as FeaturesAnnouncementIndexRouteImport } from './routes/_features/announcement/index'
import { Route as FeaturesAnalyticsIndexRouteImport } from './routes/_features/analytics/index'
import { Route as FeaturesAiWorkflowsIndexRouteImport } from './routes/_features/ai-workflows/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRouteRoute = FeaturesRouteRouteImport.update({
  id: '/_features',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FeaturesRouteRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const FeaturesTrainingsIndexRoute = FeaturesTrainingsIndexRouteImport.update({
  id: '/trainings/',
  path: '/trainings/',
  getParentRoute: () => FeaturesRouteRoute,
} as any)
const FeaturesTimesheetIndexRoute = FeaturesTimesheetIndexRouteImport.update({
  id: '/timesheet/',
  path: '/timesheet/',
  getParentRoute: () => FeaturesRouteRoute,
} as any)
const FeaturesResearchIndexRoute = FeaturesResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => FeaturesRouteRoute,
} as any)
const FeaturesProjectsIndexRoute = FeaturesProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => FeaturesRouteRoute,
} as any)
const FeaturesManageAccountsIndexRoute =
  FeaturesManageAccountsIndexRouteImport.update({
    id: '/manage-accounts/',
    path: '/manage-accounts/',
    getParentRoute: () => FeaturesRouteRoute,
  } as any)
const FeaturesGameIndexRoute = FeaturesGameIndexRouteImport.update({
  id: '/game/',
  path: '/game/',
  getParentRoute: () => FeaturesRouteRoute,
} as any)
const FeaturesEngagementsIndexRoute =
  FeaturesEngagementsIndexRouteImport.update({
    id: '/engagements/',
    path: '/engagements/',
    getParentRoute: () => FeaturesRouteRoute,
  } as any)
const FeaturesDirectoryIndexRoute = FeaturesDirectoryIndexRouteImport.update({
  id: '/directory/',
  path: '/directory/',
  getParentRoute: () => FeaturesRouteRoute,
} as any)
const FeaturesAnnouncementIndexRoute =
  FeaturesAnnouncementIndexRouteImport.update({
    id: '/announcement/',
    path: '/announcement/',
    getParentRoute: () => FeaturesRouteRoute,
  } as any)
const FeaturesAnalyticsIndexRoute = FeaturesAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => FeaturesRouteRoute,
} as any)
const FeaturesAiWorkflowsIndexRoute =
  FeaturesAiWorkflowsIndexRouteImport.update({
    id: '/ai-workflows/',
    path: '/ai-workflows/',
    getParentRoute: () => FeaturesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof FeaturesIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/': typeof AuthIndexRoute
  '/ai-workflows/': typeof FeaturesAiWorkflowsIndexRoute
  '/analytics/': typeof FeaturesAnalyticsIndexRoute
  '/announcement/': typeof FeaturesAnnouncementIndexRoute
  '/directory/': typeof FeaturesDirectoryIndexRoute
  '/engagements/': typeof FeaturesEngagementsIndexRoute
  '/game/': typeof FeaturesGameIndexRoute
  '/manage-accounts/': typeof FeaturesManageAccountsIndexRoute
  '/projects/': typeof FeaturesProjectsIndexRoute
  '/research/': typeof FeaturesResearchIndexRoute
  '/timesheet/': typeof FeaturesTimesheetIndexRoute
  '/trainings/': typeof FeaturesTrainingsIndexRoute
}
export interface FileRoutesByTo {
  '/auth/signin': typeof AuthSigninRoute
  '/': typeof FeaturesIndexRoute
  '/auth': typeof AuthIndexRoute
  '/ai-workflows': typeof FeaturesAiWorkflowsIndexRoute
  '/analytics': typeof FeaturesAnalyticsIndexRoute
  '/announcement': typeof FeaturesAnnouncementIndexRoute
  '/directory': typeof FeaturesDirectoryIndexRoute
  '/engagements': typeof FeaturesEngagementsIndexRoute
  '/game': typeof FeaturesGameIndexRoute
  '/manage-accounts': typeof FeaturesManageAccountsIndexRoute
  '/projects': typeof FeaturesProjectsIndexRoute
  '/research': typeof FeaturesResearchIndexRoute
  '/timesheet': typeof FeaturesTimesheetIndexRoute
  '/trainings': typeof FeaturesTrainingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_features': typeof FeaturesRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/_features/': typeof FeaturesIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_features/ai-workflows/': typeof FeaturesAiWorkflowsIndexRoute
  '/_features/analytics/': typeof FeaturesAnalyticsIndexRoute
  '/_features/announcement/': typeof FeaturesAnnouncementIndexRoute
  '/_features/directory/': typeof FeaturesDirectoryIndexRoute
  '/_features/engagements/': typeof FeaturesEngagementsIndexRoute
  '/_features/game/': typeof FeaturesGameIndexRoute
  '/_features/manage-accounts/': typeof FeaturesManageAccountsIndexRoute
  '/_features/projects/': typeof FeaturesProjectsIndexRoute
  '/_features/research/': typeof FeaturesResearchIndexRoute
  '/_features/timesheet/': typeof FeaturesTimesheetIndexRoute
  '/_features/trainings/': typeof FeaturesTrainingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/signin'
    | '/auth/'
    | '/ai-workflows/'
    | '/analytics/'
    | '/announcement/'
    | '/directory/'
    | '/engagements/'
    | '/game/'
    | '/manage-accounts/'
    | '/projects/'
    | '/research/'
    | '/timesheet/'
    | '/trainings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/signin'
    | '/'
    | '/auth'
    | '/ai-workflows'
    | '/analytics'
    | '/announcement'
    | '/directory'
    | '/engagements'
    | '/game'
    | '/manage-accounts'
    | '/projects'
    | '/research'
    | '/timesheet'
    | '/trainings'
  id:
    | '__root__'
    | '/_features'
    | '/auth'
    | '/auth/signin'
    | '/_features/'
    | '/auth/'
    | '/_features/ai-workflows/'
    | '/_features/analytics/'
    | '/_features/announcement/'
    | '/_features/directory/'
    | '/_features/engagements/'
    | '/_features/game/'
    | '/_features/manage-accounts/'
    | '/_features/projects/'
    | '/_features/research/'
    | '/_features/timesheet/'
    | '/_features/trainings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FeaturesRouteRoute: typeof FeaturesRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_features': {
      id: '/_features'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FeaturesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_features/': {
      id: '/_features/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof FeaturesIndexRouteImport
      parentRoute: typeof FeaturesRouteRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_features/trainings/': {
      id: '/_features/trainings/'
      path: '/trainings'
      fullPath: '/trainings/'
      preLoaderRoute: typeof FeaturesTrainingsIndexRouteImport
      parentRoute: typeof FeaturesRouteRoute
    }
    '/_features/timesheet/': {
      id: '/_features/timesheet/'
      path: '/timesheet'
      fullPath: '/timesheet/'
      preLoaderRoute: typeof FeaturesTimesheetIndexRouteImport
      parentRoute: typeof FeaturesRouteRoute
    }
    '/_features/research/': {
      id: '/_features/research/'
      path: '/research'
      fullPath: '/research/'
      preLoaderRoute: typeof FeaturesResearchIndexRouteImport
      parentRoute: typeof FeaturesRouteRoute
    }
    '/_features/projects/': {
      id: '/_features/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof FeaturesProjectsIndexRouteImport
      parentRoute: typeof FeaturesRouteRoute
    }
    '/_features/manage-accounts/': {
      id: '/_features/manage-accounts/'
      path: '/manage-accounts'
      fullPath: '/manage-accounts/'
      preLoaderRoute: typeof FeaturesManageAccountsIndexRouteImport
      parentRoute: typeof FeaturesRouteRoute
    }
    '/_features/game/': {
      id: '/_features/game/'
      path: '/game'
      fullPath: '/game/'
      preLoaderRoute: typeof FeaturesGameIndexRouteImport
      parentRoute: typeof FeaturesRouteRoute
    }
    '/_features/engagements/': {
      id: '/_features/engagements/'
      path: '/engagements'
      fullPath: '/engagements/'
      preLoaderRoute: typeof FeaturesEngagementsIndexRouteImport
      parentRoute: typeof FeaturesRouteRoute
    }
    '/_features/directory/': {
      id: '/_features/directory/'
      path: '/directory'
      fullPath: '/directory/'
      preLoaderRoute: typeof FeaturesDirectoryIndexRouteImport
      parentRoute: typeof FeaturesRouteRoute
    }
    '/_features/announcement/': {
      id: '/_features/announcement/'
      path: '/announcement'
      fullPath: '/announcement/'
      preLoaderRoute: typeof FeaturesAnnouncementIndexRouteImport
      parentRoute: typeof FeaturesRouteRoute
    }
    '/_features/analytics/': {
      id: '/_features/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof FeaturesAnalyticsIndexRouteImport
      parentRoute: typeof FeaturesRouteRoute
    }
    '/_features/ai-workflows/': {
      id: '/_features/ai-workflows/'
      path: '/ai-workflows'
      fullPath: '/ai-workflows/'
      preLoaderRoute: typeof FeaturesAiWorkflowsIndexRouteImport
      parentRoute: typeof FeaturesRouteRoute
    }
  }
}

interface FeaturesRouteRouteChildren {
  FeaturesIndexRoute: typeof FeaturesIndexRoute
  FeaturesAiWorkflowsIndexRoute: typeof FeaturesAiWorkflowsIndexRoute
  FeaturesAnalyticsIndexRoute: typeof FeaturesAnalyticsIndexRoute
  FeaturesAnnouncementIndexRoute: typeof FeaturesAnnouncementIndexRoute
  FeaturesDirectoryIndexRoute: typeof FeaturesDirectoryIndexRoute
  FeaturesEngagementsIndexRoute: typeof FeaturesEngagementsIndexRoute
  FeaturesGameIndexRoute: typeof FeaturesGameIndexRoute
  FeaturesManageAccountsIndexRoute: typeof FeaturesManageAccountsIndexRoute
  FeaturesProjectsIndexRoute: typeof FeaturesProjectsIndexRoute
  FeaturesResearchIndexRoute: typeof FeaturesResearchIndexRoute
  FeaturesTimesheetIndexRoute: typeof FeaturesTimesheetIndexRoute
  FeaturesTrainingsIndexRoute: typeof FeaturesTrainingsIndexRoute
}

const FeaturesRouteRouteChildren: FeaturesRouteRouteChildren = {
  FeaturesIndexRoute: FeaturesIndexRoute,
  FeaturesAiWorkflowsIndexRoute: FeaturesAiWorkflowsIndexRoute,
  FeaturesAnalyticsIndexRoute: FeaturesAnalyticsIndexRoute,
  FeaturesAnnouncementIndexRoute: FeaturesAnnouncementIndexRoute,
  FeaturesDirectoryIndexRoute: FeaturesDirectoryIndexRoute,
  FeaturesEngagementsIndexRoute: FeaturesEngagementsIndexRoute,
  FeaturesGameIndexRoute: FeaturesGameIndexRoute,
  FeaturesManageAccountsIndexRoute: FeaturesManageAccountsIndexRoute,
  FeaturesProjectsIndexRoute: FeaturesProjectsIndexRoute,
  FeaturesResearchIndexRoute: FeaturesResearchIndexRoute,
  FeaturesTimesheetIndexRoute: FeaturesTimesheetIndexRoute,
  FeaturesTrainingsIndexRoute: FeaturesTrainingsIndexRoute,
}

const FeaturesRouteRouteWithChildren = FeaturesRouteRoute._addFileChildren(
  FeaturesRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  FeaturesRouteRoute: FeaturesRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
