/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as FeaturesRouteRouteImport } from './routes/_features/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as FeaturesIndexRouteImport } from './routes/_features/index'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as FeaturesManageAccountsIndexRouteImport } from './routes/_features/manage-accounts/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRouteRoute = FeaturesRouteRouteImport.update({
  id: '/_features',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FeaturesRouteRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const FeaturesManageAccountsIndexRoute =
  FeaturesManageAccountsIndexRouteImport.update({
    id: '/manage-accounts/',
    path: '/manage-accounts/',
    getParentRoute: () => FeaturesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof FeaturesIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/': typeof AuthIndexRoute
  '/manage-accounts/': typeof FeaturesManageAccountsIndexRoute
}
export interface FileRoutesByTo {
  '/auth/signin': typeof AuthSigninRoute
  '/': typeof FeaturesIndexRoute
  '/auth': typeof AuthIndexRoute
  '/manage-accounts': typeof FeaturesManageAccountsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_features': typeof FeaturesRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/_features/': typeof FeaturesIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_features/manage-accounts/': typeof FeaturesManageAccountsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/auth/signin' | '/auth/' | '/manage-accounts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth/signin' | '/' | '/auth' | '/manage-accounts'
  id:
    | '__root__'
    | '/_features'
    | '/auth'
    | '/auth/signin'
    | '/_features/'
    | '/auth/'
    | '/_features/manage-accounts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FeaturesRouteRoute: typeof FeaturesRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_features': {
      id: '/_features'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FeaturesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_features/': {
      id: '/_features/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof FeaturesIndexRouteImport
      parentRoute: typeof FeaturesRouteRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_features/manage-accounts/': {
      id: '/_features/manage-accounts/'
      path: '/manage-accounts'
      fullPath: '/manage-accounts/'
      preLoaderRoute: typeof FeaturesManageAccountsIndexRouteImport
      parentRoute: typeof FeaturesRouteRoute
    }
  }
}

interface FeaturesRouteRouteChildren {
  FeaturesIndexRoute: typeof FeaturesIndexRoute
  FeaturesManageAccountsIndexRoute: typeof FeaturesManageAccountsIndexRoute
}

const FeaturesRouteRouteChildren: FeaturesRouteRouteChildren = {
  FeaturesIndexRoute: FeaturesIndexRoute,
  FeaturesManageAccountsIndexRoute: FeaturesManageAccountsIndexRoute,
}

const FeaturesRouteRouteWithChildren = FeaturesRouteRoute._addFileChildren(
  FeaturesRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  FeaturesRouteRoute: FeaturesRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
